# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'


steps:
# - task: DotNetCoreCLI@2
#   displayName: DotNet Restore
#   inputs:
#     command: restore
#     projects: '**/*.csproj'

# - task: DotNetCoreCLI@2
#   displayName: DotNet Build
#   inputs:
#     command: build
#     projects: '**/*.csproj'
#     arguments: '--configuration $(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: DotNet Test
#   inputs:
#     command: test
#     projects: '**/*Tests/*.csproj'
#     arguments: '--configuration $(buildConfiguration) --logger trx'

# - task: PublishTestResults@2
#   displayName: DotNet Test Publish
#   inputs:
#     testRunner: VSTest
#     testResultsFiles: '$(Agent.TempDirectory)/*.trx'

- task: Docker@1
  displayName: 'Docker Build'
  inputs:
    azureSubscriptionEndpoint: '54cfb10e-2e6d-4e1f-bbbf-a54d729615e4'
    azureContainerRegistry: mstyacontainerregistry.azurecr.io